# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictInt, StrictStr
from typing import Optional
from openapi_client.models.page_user_champions_league_rank_output import PageUserChampionsLeagueRankOutput
from openapi_client.models.pageable import Pageable

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class AdminChampionsLeagueUsersRankingControllerApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def find_all_user_ranking_in_branch2(
        self,
        pageable: Pageable,
        open_branch: StrictInt,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PageUserChampionsLeagueRankOutput:
        """find_all_user_ranking_in_branch2


        :param pageable: (required)
        :type pageable: Pageable
        :param open_branch: (required)
        :type open_branch: int
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_branch2_serialize(
            pageable=pageable,
            open_branch=open_branch,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def find_all_user_ranking_in_branch2_with_http_info(
        self,
        pageable: Pageable,
        open_branch: StrictInt,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PageUserChampionsLeagueRankOutput]:
        """find_all_user_ranking_in_branch2


        :param pageable: (required)
        :type pageable: Pageable
        :param open_branch: (required)
        :type open_branch: int
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_branch2_serialize(
            pageable=pageable,
            open_branch=open_branch,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def find_all_user_ranking_in_branch2_without_preload_content(
        self,
        pageable: Pageable,
        open_branch: StrictInt,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """find_all_user_ranking_in_branch2


        :param pageable: (required)
        :type pageable: Pageable
        :param open_branch: (required)
        :type open_branch: int
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_branch2_serialize(
            pageable=pageable,
            open_branch=open_branch,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _find_all_user_ranking_in_branch2_serialize(
        self,
        pageable,
        open_branch,
        customer_id,
        name,
        family_name,
        min_gem,
        max_gem,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if pageable is not None:
            
            _query_params.append(('pageable', pageable))
            
        if open_branch is not None:
            
            _query_params.append(('openBranch', open_branch))
            
        if customer_id is not None:
            
            _query_params.append(('customerId', customer_id))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if family_name is not None:
            
            _query_params.append(('familyName', family_name))
            
        if min_gem is not None:
            
            _query_params.append(('minGem', min_gem))
            
        if max_gem is not None:
            
            _query_params.append(('maxGem', max_gem))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    '*/*'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/admin/champions-league/ranking/branch',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def find_all_user_ranking_in_country3(
        self,
        pageable: Pageable,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PageUserChampionsLeagueRankOutput:
        """find_all_user_ranking_in_country3


        :param pageable: (required)
        :type pageable: Pageable
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_country3_serialize(
            pageable=pageable,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def find_all_user_ranking_in_country3_with_http_info(
        self,
        pageable: Pageable,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PageUserChampionsLeagueRankOutput]:
        """find_all_user_ranking_in_country3


        :param pageable: (required)
        :type pageable: Pageable
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_country3_serialize(
            pageable=pageable,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def find_all_user_ranking_in_country3_without_preload_content(
        self,
        pageable: Pageable,
        customer_id: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        family_name: Optional[StrictStr] = None,
        min_gem: Optional[StrictInt] = None,
        max_gem: Optional[StrictInt] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """find_all_user_ranking_in_country3


        :param pageable: (required)
        :type pageable: Pageable
        :param customer_id:
        :type customer_id: str
        :param name:
        :type name: str
        :param family_name:
        :type family_name: str
        :param min_gem:
        :type min_gem: int
        :param max_gem:
        :type max_gem: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._find_all_user_ranking_in_country3_serialize(
            pageable=pageable,
            customer_id=customer_id,
            name=name,
            family_name=family_name,
            min_gem=min_gem,
            max_gem=max_gem,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageUserChampionsLeagueRankOutput",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _find_all_user_ranking_in_country3_serialize(
        self,
        pageable,
        customer_id,
        name,
        family_name,
        min_gem,
        max_gem,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if pageable is not None:
            
            _query_params.append(('pageable', pageable))
            
        if customer_id is not None:
            
            _query_params.append(('customerId', customer_id))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if family_name is not None:
            
            _query_params.append(('familyName', family_name))
            
        if min_gem is not None:
            
            _query_params.append(('minGem', min_gem))
            
        if max_gem is not None:
            
            _query_params.append(('maxGem', max_gem))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    '*/*'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/admin/champions-league/ranking/country',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


