# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.terminal_score_output import TerminalScoreOutput

class TestTerminalScoreOutput(unittest.TestCase):
    """TerminalScoreOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminalScoreOutput:
        """Test TerminalScoreOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminalScoreOutput`
        """
        model = TerminalScoreOutput()
        if include_optional:
            return TerminalScoreOutput(
                terminal = openapi_client.models.terminal_output.TerminalOutput(
                    terminal_code = '', 
                    account_number = '', ),
                score = 56
            )
        else:
            return TerminalScoreOutput(
        )
        """

    def testTerminalScoreOutput(self):
        """Test TerminalScoreOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
