# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_champions_league_badge_description_controller_api import AdminChampionsLeagueBadgeDescriptionControllerApi


class TestAdminChampionsLeagueBadgeDescriptionControllerApi(unittest.TestCase):
    """AdminChampionsLeagueBadgeDescriptionControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminChampionsLeagueBadgeDescriptionControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_badge_description(self) -> None:
        """Test case for get_badge_description

        """
        pass

    def test_update_badge_description(self) -> None:
        """Test case for update_badge_description

        """
        pass


if __name__ == '__main__':
    unittest.main()
