# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_all_users_request import GetAllUsersRequest

class TestGetAllUsersRequest(unittest.TestCase):
    """GetAllUsersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllUsersRequest:
        """Test GetAllUsersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllUsersRequest`
        """
        model = GetAllUsersRequest()
        if include_optional:
            return GetAllUsersRequest(
                input = openapi_client.models.admin_club_ayn_search_input.AdminClubAynSearchInput(
                    customer_number = 56, 
                    customer_level = '', 
                    mobile_number = '', 
                    first_name = '', 
                    last_name = '', 
                    birth_day = 56, 
                    sex = '', 
                    open_branch = 56, 
                    from_date = 56, 
                    until_date = 56, 
                    field = 'AYN_POS_TR', 
                    min_value = 56, 
                    max_value = 56, ),
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort.Sort(
                        sorted = True, 
                        unsorted = True, 
                        empty = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    paged = True, 
                    unpaged = True, )
            )
        else:
            return GetAllUsersRequest(
        )
        """

    def testGetAllUsersRequest(self):
        """Test GetAllUsersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
