# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.admin_user_management_output import AdminUserManagementOutput

class TestAdminUserManagementOutput(unittest.TestCase):
    """AdminUserManagementOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminUserManagementOutput:
        """Test AdminUserManagementOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminUserManagementOutput`
        """
        model = AdminUserManagementOutput()
        if include_optional:
            return AdminUserManagementOutput(
                first_name = '',
                last_name = '',
                customer_number = '',
                customer_level = '',
                mobile_numbers = '',
                birth_date = '',
                sex = '',
                open_branch = 56,
                amount = 56
            )
        else:
            return AdminUserManagementOutput(
        )
        """

    def testAdminUserManagementOutput(self):
        """Test AdminUserManagementOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
