# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_insurance_ticket_purchase_controller_api import AdminInsuranceTicketPurchaseControllerApi


class TestAdminInsuranceTicketPurchaseControllerApi(unittest.TestCase):
    """AdminInsuranceTicketPurchaseControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminInsuranceTicketPurchaseControllerApi()

    def tearDown(self) -> None:
        pass

    def test_fd(self) -> None:
        """Test case for fd

        """
        pass


if __name__ == '__main__':
    unittest.main()
