# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.send_otp_input import SendOtpInput

class TestSendOtpInput(unittest.TestCase):
    """SendOtpInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendOtpInput:
        """Test SendOtpInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendOtpInput`
        """
        model = SendOtpInput()
        if include_optional:
            return SendOtpInput(
                cif = ''
            )
        else:
            return SendOtpInput(
                cif = '',
        )
        """

    def testSendOtpInput(self):
        """Test SendOtpInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
