# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_level_history_response_dto import CustomerLevelHistoryResponseDTO

class TestCustomerLevelHistoryResponseDTO(unittest.TestCase):
    """CustomerLevelHistoryResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerLevelHistoryResponseDTO:
        """Test CustomerLevelHistoryResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerLevelHistoryResponseDTO`
        """
        model = CustomerLevelHistoryResponseDTO()
        if include_optional:
            return CustomerLevelHistoryResponseDTO(
                id = 56,
                user_id = 56,
                customer_number = '',
                old_level = '',
                new_level = '',
                change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                score = 56,
                changed_by_user_id = 56,
                change_reason = ''
            )
        else:
            return CustomerLevelHistoryResponseDTO(
        )
        """

    def testCustomerLevelHistoryResponseDTO(self):
        """Test CustomerLevelHistoryResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
