# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.admin_online_center_output2 import AdminOnlineCenterOutput2

class TestAdminOnlineCenterOutput2(unittest.TestCase):
    """AdminOnlineCenterOutput2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminOnlineCenterOutput2:
        """Test AdminOnlineCenterOutput2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminOnlineCenterOutput2`
        """
        model = AdminOnlineCenterOutput2()
        if include_optional:
            return AdminOnlineCenterOutput2(
                id = 56,
                title = '',
                rate = 1.337,
                rate_count = 56,
                required_score = 56,
                logo_id = 56,
                discount_description = '',
                online_center_description = '',
                ticket_help = '',
                expires_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                category_id = 56,
                user_level = '',
                comment_count = 56,
                purchase_code_count = 56,
                url = '',
                url_title = '',
                active = True,
                purchase_codes = [
                    ''
                    ],
                comments = [
                    openapi_client.models.comment_output.CommentOutput(
                        id = 56, 
                        name = '', 
                        customer_number = '', 
                        mobile_numbers = '', 
                        profile_picture_id = 56, 
                        user_level_type = '', 
                        rate = 56, 
                        message = '', 
                        shop_title = '', 
                        logo_id = 56, 
                        create_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        comment_condition = 'ACCEPT', )
                    ]
            )
        else:
            return AdminOnlineCenterOutput2(
        )
        """

    def testAdminOnlineCenterOutput2(self):
        """Test AdminOnlineCenterOutput2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
