# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.home_output import HomeOutput

class TestHomeOutput(unittest.TestCase):
    """HomeOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HomeOutput:
        """Test HomeOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HomeOutput`
        """
        model = HomeOutput()
        if include_optional:
            return HomeOutput(
                banners = [
                    openapi_client.models.banner_output.BannerOutput(
                        id = 56, 
                        image_id = 56, 
                        title = '', 
                        message = '', 
                        uri = '', 
                        type = 'HOME', )
                    ],
                user_home = openapi_client.models.user_home_output.UserHomeOutput(
                    profile_picture_id = 56, 
                    score = 56, 
                    gem = 56, 
                    level_picture_id = 56, 
                    level_icon_id = 56, 
                    level_name = '', 
                    level_title = '', 
                    theme = 'PLATINUM', 
                    last_score_update = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    customer_id = '', ),
                total_score = 56,
                total_loan_score = 56,
                total_lottery_score = 56
            )
        else:
            return HomeOutput(
        )
        """

    def testHomeOutput(self):
        """Test HomeOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
