# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.charity_output import CharityOutput

class TestCharityOutput(unittest.TestCase):
    """CharityOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharityOutput:
        """Test CharityOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharityOutput`
        """
        model = CharityOutput()
        if include_optional:
            return CharityOutput(
                id = 56,
                logo_id = 56,
                image_id = 56,
                title = '',
                charity_description = '',
                gift_description = '',
                required_score = 56,
                donation_scores = 56,
                user_level = '',
                display_order = 56,
                complete = True,
                url = '',
                url_title = '',
                active = True,
                main = True
            )
        else:
            return CharityOutput(
        )
        """

    def testCharityOutput(self):
        """Test CharityOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
