# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prize_output import PrizeOutput

class TestPrizeOutput(unittest.TestCase):
    """PrizeOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrizeOutput:
        """Test PrizeOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrizeOutput`
        """
        model = PrizeOutput()
        if include_optional:
            return PrizeOutput(
                id = 56,
                lottery_id = 56,
                winner = openapi_client.models.user_prize_output.UserPrizeOutput(
                    id = 56, 
                    name = '', 
                    family_name = '', 
                    user_level_type = '', 
                    score = 56, 
                    gem = 56, 
                    customer_id = '', 
                    is_show_name = True, 
                    national_id = '', 
                    mobile_phone = '', ),
                user_id = 56,
                user_name = '',
                user_family_name = '',
                user_level_type = '',
                user_score = 56,
                user_gem = 56,
                customer_id = '',
                user_is_show_name = True,
                user_national_id = '',
                user_mobile_phone = '',
                user_rank = '',
                award_description = '',
                prize_order = 56,
                user_logged = True,
                winner_index = ''
            )
        else:
            return PrizeOutput(
        )
        """

    def testPrizeOutput(self):
        """Test PrizeOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
