# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mission_optional_requirement_output import MissionOptionalRequirementOutput

class TestMissionOptionalRequirementOutput(unittest.TestCase):
    """MissionOptionalRequirementOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MissionOptionalRequirementOutput:
        """Test MissionOptionalRequirementOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MissionOptionalRequirementOutput`
        """
        model = MissionOptionalRequirementOutput()
        if include_optional:
            return MissionOptionalRequirementOutput(
                type = 'IN_APP',
                score_type = '',
                target_id = 56,
                needed_score = 56
            )
        else:
            return MissionOptionalRequirementOutput(
        )
        """

    def testMissionOptionalRequirementOutput(self):
        """Test MissionOptionalRequirementOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
