# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_iran_mall_cinema_ticket_purchase_controller_api import AdminIranMallCinemaTicketPurchaseControllerApi


class TestAdminIranMallCinemaTicketPurchaseControllerApi(unittest.TestCase):
    """AdminIranMallCinemaTicketPurchaseControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminIranMallCinemaTicketPurchaseControllerApi()

    def tearDown(self) -> None:
        pass

    def test_find_buyers_user_by_iran_mall_cinema_id(self) -> None:
        """Test case for find_buyers_user_by_iran_mall_cinema_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
