# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iran_card_feature_ticket_output import IranCardFeatureTicketOutput

class TestIranCardFeatureTicketOutput(unittest.TestCase):
    """IranCardFeatureTicketOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IranCardFeatureTicketOutput:
        """Test IranCardFeatureTicketOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IranCardFeatureTicketOutput`
        """
        model = IranCardFeatureTicketOutput()
        if include_optional:
            return IranCardFeatureTicketOutput(
                id = 56,
                image_id = 56,
                title = '',
                category_name = ''
            )
        else:
            return IranCardFeatureTicketOutput(
        )
        """

    def testIranCardFeatureTicketOutput(self):
        """Test IranCardFeatureTicketOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
