# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_charity_controller_api import AdminCharityControllerApi


class TestAdminCharityControllerApi(unittest.TestCase):
    """AdminCharityControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminCharityControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_charity(self) -> None:
        """Test case for create_charity

        """
        pass

    def test_delete_charity_by_id(self) -> None:
        """Test case for delete_charity_by_id

        """
        pass

    def test_find_all_charities_by_display_order(self) -> None:
        """Test case for find_all_charities_by_display_order

        """
        pass

    def test_find_all_charities_by_user_level_and_title(self) -> None:
        """Test case for find_all_charities_by_user_level_and_title

        """
        pass

    def test_find_charity_by_id1(self) -> None:
        """Test case for find_charity_by_id1

        """
        pass

    def test_update_charity_by_id(self) -> None:
        """Test case for update_charity_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
