# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lottery_black_list_output import LotteryBlackListOutput

class TestLotteryBlackListOutput(unittest.TestCase):
    """LotteryBlackListOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotteryBlackListOutput:
        """Test LotteryBlackListOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotteryBlackListOutput`
        """
        model = LotteryBlackListOutput()
        if include_optional:
            return LotteryBlackListOutput(
                name = '',
                level = '',
                create_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                customer_id = '',
                lottery_title = ''
            )
        else:
            return LotteryBlackListOutput(
        )
        """

    def testLotteryBlackListOutput(self):
        """Test LotteryBlackListOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
