# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.champions_league_lucky_wheel_output import ChampionsLeagueLuckyWheelOutput

class TestChampionsLeagueLuckyWheelOutput(unittest.TestCase):
    """ChampionsLeagueLuckyWheelOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChampionsLeagueLuckyWheelOutput:
        """Test ChampionsLeagueLuckyWheelOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChampionsLeagueLuckyWheelOutput`
        """
        model = ChampionsLeagueLuckyWheelOutput()
        if include_optional:
            return ChampionsLeagueLuckyWheelOutput(
                id = 56,
                image_id = 56,
                description = '',
                gem_required_to_re_participate = 56,
                free = True,
                items = [
                    openapi_client.models.champions_league_lucky_wheel_item_output.ChampionsLeagueLuckyWheelItemOutput(
                        id = 56, 
                        lucky_wheel = 56, 
                        prize_title = '', 
                        display_percent = 56, 
                        prize_type = 'SCORE', )
                    ]
            )
        else:
            return ChampionsLeagueLuckyWheelOutput(
        )
        """

    def testChampionsLeagueLuckyWheelOutput(self):
        """Test ChampionsLeagueLuckyWheelOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
