# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.member_iran_card_home_controller_api import MemberIranCardHomeControllerApi


class TestMemberIranCardHomeControllerApi(unittest.TestCase):
    """MemberIranCardHomeControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberIranCardHomeControllerApi()

    def tearDown(self) -> None:
        pass

    def test_home(self) -> None:
        """Test case for home

        """
        pass


if __name__ == '__main__':
    unittest.main()
