# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.lottery_home_output import LotteryHomeOutput

class TestLotteryHomeOutput(unittest.TestCase):
    """LotteryHomeOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotteryHomeOutput:
        """Test LotteryHomeOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotteryHomeOutput`
        """
        model = LotteryHomeOutput()
        if include_optional:
            return LotteryHomeOutput(
                lottery_banners = [
                    openapi_client.models.banner_output.BannerOutput(
                        id = 56, 
                        image_id = 56, 
                        title = '', 
                        message = '', 
                        uri = '', 
                        type = 'HOME', )
                    ],
                lottery_tickets = [
                    openapi_client.models.lottery_ticket_output.LotteryTicketOutput(
                        id = 56, 
                        image_id = 56, 
                        title = '', 
                        description = '', 
                        lottery_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finish = True, )
                    ]
            )
        else:
            return LotteryHomeOutput(
        )
        """

    def testLotteryHomeOutput(self):
        """Test LotteryHomeOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
