# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.spend_score_output import SpendScoreOutput

class TestSpendScoreOutput(unittest.TestCase):
    """SpendScoreOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpendScoreOutput:
        """Test SpendScoreOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpendScoreOutput`
        """
        model = SpendScoreOutput()
        if include_optional:
            return SpendScoreOutput(
                banner = openapi_client.models.banner_output.BannerOutput(
                    id = 56, 
                    image_id = 56, 
                    title = '', 
                    message = '', 
                    uri = '', 
                    type = 'HOME', ),
                user_spend_score = openapi_client.models.user_spend_score_output.UserSpendScoreOutput(
                    id = 56, 
                    score = 56, 
                    level_picture_id = 56, 
                    level_icon_id = 56, 
                    level_name = '', 
                    level_title = '', 
                    theme = 'PLATINUM', 
                    expires_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return SpendScoreOutput(
        )
        """

    def testSpendScoreOutput(self):
        """Test SpendScoreOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
