# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_other_lottery_controller_api import AdminOtherLotteryControllerApi


class TestAdminOtherLotteryControllerApi(unittest.TestCase):
    """AdminOtherLotteryControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminOtherLotteryControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_lottery(self) -> None:
        """Test case for create_lottery

        """
        pass

    def test_delete_lottery_by_id(self) -> None:
        """Test case for delete_lottery_by_id

        """
        pass

    def test_do_champions_league_lottery(self) -> None:
        """Test case for do_champions_league_lottery

        """
        pass

    def test_find_lottery_by_id2(self) -> None:
        """Test case for find_lottery_by_id2

        """
        pass

    def test_load_all_by_type3(self) -> None:
        """Test case for load_all_by_type3

        """
        pass

    def test_update_lottery_by_id(self) -> None:
        """Test case for update_lottery_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
