# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_offline_rule_engine_controller_api import AdminOfflineRuleEngineControllerApi


class TestAdminOfflineRuleEngineControllerApi(unittest.TestCase):
    """AdminOfflineRuleEngineControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminOfflineRuleEngineControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        """
        pass

    def test_find_by_id(self) -> None:
        """Test case for find_by_id

        """
        pass

    def test_update(self) -> None:
        """Test case for update

        """
        pass


if __name__ == '__main__':
    unittest.main()
