# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.online_center_ticket_purchase_output import OnlineCenterTicketPurchaseOutput

class TestOnlineCenterTicketPurchaseOutput(unittest.TestCase):
    """OnlineCenterTicketPurchaseOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnlineCenterTicketPurchaseOutput:
        """Test OnlineCenterTicketPurchaseOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnlineCenterTicketPurchaseOutput`
        """
        model = OnlineCenterTicketPurchaseOutput()
        if include_optional:
            return OnlineCenterTicketPurchaseOutput(
                id = 56,
                name = '',
                purchase_code = '',
                event_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                purchase_type = 'ONLINE_CENTER'
            )
        else:
            return OnlineCenterTicketPurchaseOutput(
        )
        """

    def testOnlineCenterTicketPurchaseOutput(self):
        """Test OnlineCenterTicketPurchaseOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
