# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_lucky_wheel_participate_output import ReportLuckyWheelParticipateOutput

class TestReportLuckyWheelParticipateOutput(unittest.TestCase):
    """ReportLuckyWheelParticipateOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportLuckyWheelParticipateOutput:
        """Test ReportLuckyWheelParticipateOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportLuckyWheelParticipateOutput`
        """
        model = ReportLuckyWheelParticipateOutput()
        if include_optional:
            return ReportLuckyWheelParticipateOutput(
                id = 56,
                first_name = '',
                last_name = '',
                user_level_type = '',
                prize_title = '',
                customer_number = 56,
                spin_sum = 56,
                spin_count = 56
            )
        else:
            return ReportLuckyWheelParticipateOutput(
        )
        """

    def testReportLuckyWheelParticipateOutput(self):
        """Test ReportLuckyWheelParticipateOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
