# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.voting_option_stats_output import VotingOptionStatsOutput

class TestVotingOptionStatsOutput(unittest.TestCase):
    """VotingOptionStatsOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VotingOptionStatsOutput:
        """Test VotingOptionStatsOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VotingOptionStatsOutput`
        """
        model = VotingOptionStatsOutput()
        if include_optional:
            return VotingOptionStatsOutput(
                count = 56,
                option_title = '',
                option_id = 56
            )
        else:
            return VotingOptionStatsOutput(
        )
        """

    def testVotingOptionStatsOutput(self):
        """Test VotingOptionStatsOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
