# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cas_authentication_controller_api import CasAuthenticationControllerApi


class TestCasAuthenticationControllerApi(unittest.TestCase):
    """CasAuthenticationControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CasAuthenticationControllerApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate(self) -> None:
        """Test case for authenticate

        """
        pass

    def test_login_with_cas(self) -> None:
        """Test case for login_with_cas

        """
        pass


if __name__ == '__main__':
    unittest.main()
