# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_customer_level_indicator_controller_api import AdminCustomerLevelIndicatorControllerApi


class TestAdminCustomerLevelIndicatorControllerApi(unittest.TestCase):
    """AdminCustomerLevelIndicatorControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminCustomerLevelIndicatorControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create2(self) -> None:
        """Test case for create2

        """
        pass

    def test_delete_customer_level_indicator_by_id(self) -> None:
        """Test case for delete_customer_level_indicator_by_id

        """
        pass

    def test_find_all5(self) -> None:
        """Test case for find_all5

        """
        pass

    def test_find_all_type(self) -> None:
        """Test case for find_all_type

        """
        pass

    def test_find_by_id3(self) -> None:
        """Test case for find_by_id3

        """
        pass

    def test_update2(self) -> None:
        """Test case for update2

        """
        pass


if __name__ == '__main__':
    unittest.main()
