# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_champions_league_lucky_wheel_item_controller_api import AdminChampionsLeagueLuckyWheelItemControllerApi


class TestAdminChampionsLeagueLuckyWheelItemControllerApi(unittest.TestCase):
    """AdminChampionsLeagueLuckyWheelItemControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminChampionsLeagueLuckyWheelItemControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_champions_league_lucky_wheel_item(self) -> None:
        """Test case for create_champions_league_lucky_wheel_item

        """
        pass

    def test_delete_champions_league_lucky_wheel_item_by_id(self) -> None:
        """Test case for delete_champions_league_lucky_wheel_item_by_id

        """
        pass

    def test_find_champions_league_lucky_wheel_item_by_id(self) -> None:
        """Test case for find_champions_league_lucky_wheel_item_by_id

        """
        pass

    def test_load_all_by_lucky_wheel_id(self) -> None:
        """Test case for load_all_by_lucky_wheel_id

        """
        pass

    def test_update_champions_league_lucky_wheel_item_by_id(self) -> None:
        """Test case for update_champions_league_lucky_wheel_item_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
