# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_output import UserOutput

class TestUserOutput(unittest.TestCase):
    """UserOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserOutput:
        """Test UserOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserOutput`
        """
        model = UserOutput()
        if include_optional:
            return UserOutput(
                id = 56,
                username = '',
                name = '',
                family_name = '',
                user_level_type = '',
                score = 56,
                gem = 56,
                customer_id = '',
                national_id = '',
                phone = '',
                roles = [
                    ''
                    ],
                is_account_non_expired = True,
                is_account_non_locked = True,
                is_credentials_non_expired = True,
                is_enabled = True
            )
        else:
            return UserOutput(
        )
        """

    def testUserOutput(self):
        """Test UserOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
