# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.club_info import ClubInfo

class TestClubInfo(unittest.TestCase):
    """ClubInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClubInfo:
        """Test ClubInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClubInfo`
        """
        model = ClubInfo()
        if include_optional:
            return ClubInfo(
                id = 56,
                name = '',
                title = '',
                icon_url = '',
                logo_url = '',
                admin_name = '',
                admin_icon_url = '',
                admin_logo_url = '',
                theme = ''
            )
        else:
            return ClubInfo(
        )
        """

    def testClubInfo(self):
        """Test ClubInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
