# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.samin_loan_score_type_input import SaminLoanScoreTypeInput

class TestSaminLoanScoreTypeInput(unittest.TestCase):
    """SaminLoanScoreTypeInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SaminLoanScoreTypeInput:
        """Test SaminLoanScoreTypeInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SaminLoanScoreTypeInput`
        """
        model = SaminLoanScoreTypeInput()
        if include_optional:
            return SaminLoanScoreTypeInput(
                rate = 56,
                refund = 56,
                period = 56,
                account_number = ''
            )
        else:
            return SaminLoanScoreTypeInput(
        )
        """

    def testSaminLoanScoreTypeInput(self):
        """Test SaminLoanScoreTypeInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
