# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_level_request_dto import CustomerLevelRequestDTO

class TestCustomerLevelRequestDTO(unittest.TestCase):
    """CustomerLevelRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerLevelRequestDTO:
        """Test CustomerLevelRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerLevelRequestDTO`
        """
        model = CustomerLevelRequestDTO()
        if include_optional:
            return CustomerLevelRequestDTO(
                name = '',
                title = '',
                min_total_score = 0,
                max_total_score = 0,
                profile_logo_id = 56,
                profile_icon_id = 56,
                description = '',
                theme = 'PLATINUM',
                effective_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                disable_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CustomerLevelRequestDTO(
                name = '',
                title = '',
                min_total_score = 0,
                max_total_score = 0,
                profile_logo_id = 56,
                profile_icon_id = 56,
                effective_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCustomerLevelRequestDTO(self):
        """Test CustomerLevelRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
