# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_to_friend_input import GiftToFriendInput

class TestGiftToFriendInput(unittest.TestCase):
    """GiftToFriendInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftToFriendInput:
        """Test GiftToFriendInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftToFriendInput`
        """
        model = GiftToFriendInput()
        if include_optional:
            return GiftToFriendInput(
                customer_id = '',
                score_count = 1
            )
        else:
            return GiftToFriendInput(
                customer_id = '',
                score_count = 1,
        )
        """

    def testGiftToFriendInput(self):
        """Test GiftToFriendInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
