# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.page_user_champions_league_rank_output import PageUserChampionsLeagueRankOutput

class TestPageUserChampionsLeagueRankOutput(unittest.TestCase):
    """PageUserChampionsLeagueRankOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageUserChampionsLeagueRankOutput:
        """Test PageUserChampionsLeagueRankOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageUserChampionsLeagueRankOutput`
        """
        model = PageUserChampionsLeagueRankOutput()
        if include_optional:
            return PageUserChampionsLeagueRankOutput(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.user_champions_league_rank_output_.UserChampionsLeagueRankOutput_(
                        full_name = '', 
                        rank = 56, 
                        customer_level = '', 
                        customer_id = 56, 
                        gem_counter = 56, )
                    ],
                number = 56,
                sort = openapi_client.models.sort.Sort(
                    sorted = True, 
                    unsorted = True, 
                    empty = True, ),
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort.Sort(
                        sorted = True, 
                        unsorted = True, 
                        empty = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    paged = True, 
                    unpaged = True, ),
                number_of_elements = 56,
                first = True,
                last = True,
                empty = True
            )
        else:
            return PageUserChampionsLeagueRankOutput(
        )
        """

    def testPageUserChampionsLeagueRankOutput(self):
        """Test PageUserChampionsLeagueRankOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
