# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_users_score_input import ReportUsersScoreInput

class TestReportUsersScoreInput(unittest.TestCase):
    """ReportUsersScoreInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportUsersScoreInput:
        """Test ReportUsersScoreInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportUsersScoreInput`
        """
        model = ReportUsersScoreInput()
        if include_optional:
            return ReportUsersScoreInput(
                first_name = '',
                last_name = '',
                customer_number = 56,
                customer_level = '',
                mobile_number = '',
                from_sign_up_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                until_sign_up_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sex = '',
                open_branch = 56,
                terminal_id = '',
                account_id = '',
                is_acceptor = True,
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                until_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                var_field = '',
                type = 'IN_APP_SCORE'
            )
        else:
            return ReportUsersScoreInput(
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                until_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                var_field = '',
                type = 'IN_APP_SCORE',
        )
        """

    def testReportUsersScoreInput(self):
        """Test ReportUsersScoreInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
