# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_insurance_category_controller_api import AdminInsuranceCategoryControllerApi


class TestAdminInsuranceCategoryControllerApi(unittest.TestCase):
    """AdminInsuranceCategoryControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminInsuranceCategoryControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_insurance_category(self) -> None:
        """Test case for create_insurance_category

        """
        pass

    def test_delete_insurance_category_by_id(self) -> None:
        """Test case for delete_insurance_category_by_id

        """
        pass

    def test_find_insurance_category_by_id1(self) -> None:
        """Test case for find_insurance_category_by_id1

        """
        pass

    def test_load_all23(self) -> None:
        """Test case for load_all23

        """
        pass

    def test_update_insurance_category_by_id(self) -> None:
        """Test case for update_insurance_category_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
