# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_app_user_output import ReportAppUserOutput

class TestReportAppUserOutput(unittest.TestCase):
    """ReportAppUserOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportAppUserOutput:
        """Test ReportAppUserOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportAppUserOutput`
        """
        model = ReportAppUserOutput()
        if include_optional:
            return ReportAppUserOutput(
                id = 56,
                first_name = '',
                last_name = '',
                customer_number = 56,
                user_level_type = '',
                mobile_number = '',
                sign_up_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sex = '',
                open_branch = 56
            )
        else:
            return ReportAppUserOutput(
        )
        """

    def testReportAppUserOutput(self):
        """Test ReportAppUserOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
