# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.page_create_branch_output import PageCreateBranchOutput

class TestPageCreateBranchOutput(unittest.TestCase):
    """PageCreateBranchOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageCreateBranchOutput:
        """Test PageCreateBranchOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageCreateBranchOutput`
        """
        model = PageCreateBranchOutput()
        if include_optional:
            return PageCreateBranchOutput(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.create_branch_output.CreateBranchOutput(
                        id = 56, 
                        code = '', 
                        name = '', 
                        full_address = '', 
                        state_name = '', 
                        city_name = '', 
                        state_id = 56, 
                        city_id = 56, 
                        title = '', 
                        contacts = [
                            openapi_client.models.create_contact_output.CreateContactOutput(
                                id = 56, 
                                value = '', 
                                type = '', )
                            ], )
                    ],
                number = 56,
                sort = openapi_client.models.sort.Sort(
                    sorted = True, 
                    unsorted = True, 
                    empty = True, ),
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort.Sort(
                        sorted = True, 
                        unsorted = True, 
                        empty = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    paged = True, 
                    unpaged = True, ),
                number_of_elements = 56,
                first = True,
                last = True,
                empty = True
            )
        else:
            return PageCreateBranchOutput(
        )
        """

    def testPageCreateBranchOutput(self):
        """Test PageCreateBranchOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
