# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.member_voting_controller_api import MemberVotingControllerApi


class TestMemberVotingControllerApi(unittest.TestCase):
    """MemberVotingControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberVotingControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_active_votings(self) -> None:
        """Test case for get_active_votings

        """
        pass

    def test_update_answer(self) -> None:
        """Test case for update_answer

        """
        pass


if __name__ == '__main__':
    unittest.main()
