# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_mission_controller_api import AdminMissionControllerApi


class TestAdminMissionControllerApi(unittest.TestCase):
    """AdminMissionControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminMissionControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_mission(self) -> None:
        """Test case for create_mission

        """
        pass

    def test_delete_by_id(self) -> None:
        """Test case for delete_by_id

        """
        pass

    def test_find_by_id1(self) -> None:
        """Test case for find_by_id1

        """
        pass

    def test_load_all14(self) -> None:
        """Test case for load_all14

        """
        pass

    def test_load_missions_meta_data(self) -> None:
        """Test case for load_missions_meta_data

        """
        pass

    def test_update_mission(self) -> None:
        """Test case for update_mission

        """
        pass


if __name__ == '__main__':
    unittest.main()
