# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_club_ayn_controller_api import AdminClubAynControllerApi


class TestAdminClubAynControllerApi(unittest.TestCase):
    """AdminClubAynControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminClubAynControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_users(self) -> None:
        """Test case for get_all_users

        """
        pass


if __name__ == '__main__':
    unittest.main()
