# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_champions_league_lottery_controller_api import AdminChampionsLeagueLotteryControllerApi


class TestAdminChampionsLeagueLotteryControllerApi(unittest.TestCase):
    """AdminChampionsLeagueLotteryControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminChampionsLeagueLotteryControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_lottery2(self) -> None:
        """Test case for create_lottery2

        """
        pass

    def test_delete_lottery_by_id2(self) -> None:
        """Test case for delete_lottery_by_id2

        """
        pass

    def test_do_champions_league_lottery1(self) -> None:
        """Test case for do_champions_league_lottery1

        """
        pass

    def test_find_lottery_by_id4(self) -> None:
        """Test case for find_lottery_by_id4

        """
        pass

    def test_load_all_by_type5(self) -> None:
        """Test case for load_all_by_type5

        """
        pass

    def test_update_lottery_by_id2(self) -> None:
        """Test case for update_lottery_by_id2

        """
        pass


if __name__ == '__main__':
    unittest.main()
