# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.voting_stats_output import VotingStatsOutput

class TestVotingStatsOutput(unittest.TestCase):
    """VotingStatsOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VotingStatsOutput:
        """Test VotingStatsOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VotingStatsOutput`
        """
        model = VotingStatsOutput()
        if include_optional:
            return VotingStatsOutput(
                voting_title = '',
                vote_count = 56,
                stats = [
                    openapi_client.models.voting_option_stats_output.VotingOptionStatsOutput(
                        count = 56, 
                        option_title = '', 
                        option_id = 56, )
                    ],
                stats_detail = [
                    openapi_client.models.voting_answer_excel_detail_output.VotingAnswerExcelDetailOutput(
                        name = '', 
                        national_id = '', 
                        user_level_type = '', 
                        family_name = '', 
                        username = '', 
                        score = 56, 
                        gem = 56, 
                        customer_id = '', 
                        voting_option_title = '', )
                    ]
            )
        else:
            return VotingStatsOutput(
        )
        """

    def testVotingStatsOutput(self):
        """Test VotingStatsOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
