# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.increase_score_bank_article_output import IncreaseScoreBankArticleOutput

class TestIncreaseScoreBankArticleOutput(unittest.TestCase):
    """IncreaseScoreBankArticleOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IncreaseScoreBankArticleOutput:
        """Test IncreaseScoreBankArticleOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IncreaseScoreBankArticleOutput`
        """
        model = IncreaseScoreBankArticleOutput()
        if include_optional:
            return IncreaseScoreBankArticleOutput(
                id = 56,
                image_id = 56,
                logo_id = 56,
                main = True,
                show = True,
                title = '',
                description = '',
                body = '',
                background_id = 56,
                increase_score_bank_article_type = 'DEPOSIT'
            )
        else:
            return IncreaseScoreBankArticleOutput(
        )
        """

    def testIncreaseScoreBankArticleOutput(self):
        """Test IncreaseScoreBankArticleOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
