# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.page_notification_output import PageNotificationOutput

class TestPageNotificationOutput(unittest.TestCase):
    """PageNotificationOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageNotificationOutput:
        """Test PageNotificationOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageNotificationOutput`
        """
        model = PageNotificationOutput()
        if include_optional:
            return PageNotificationOutput(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.notification_output.NotificationOutput(
                        id = 56, 
                        title = '', 
                        message = '', 
                        seen = True, 
                        create_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        seen_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        customer_id = '', )
                    ],
                number = 56,
                sort = openapi_client.models.sort.Sort(
                    sorted = True, 
                    unsorted = True, 
                    empty = True, ),
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort.Sort(
                        sorted = True, 
                        unsorted = True, 
                        empty = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    paged = True, 
                    unpaged = True, ),
                number_of_elements = 56,
                first = True,
                last = True,
                empty = True
            )
        else:
            return PageNotificationOutput(
        )
        """

    def testPageNotificationOutput(self):
        """Test PageNotificationOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
