# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class AdminUserInput(BaseModel):
    """
    AdminUserInput
    """ # noqa: E501
    username: StrictStr
    password: StrictStr
    confirm_password: StrictStr = Field(alias="confirmPassword")
    name: StrictStr
    last_name: StrictStr = Field(alias="lastName")
    is_enabled: StrictBool = Field(alias="isEnabled")
    roles: List[StrictStr]
    __properties: ClassVar[List[str]] = ["username", "password", "confirmPassword", "name", "lastName", "isEnabled", "roles"]

    @field_validator('roles')
    def roles_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['SUPER_ADMIN', 'BANNER_ADMIN', 'COMMENT_OPERATOR', 'NOTIFICATION_ADMIN', 'VIEWER', 'MEMBER', 'WEB_SERVICE_ADMIN', 'RULES_ENGINE_ADMIN', 'BRANCH_ADMIN', 'BRANCH_EMPLOYEE']):
                raise ValueError("each list item must be one of ('SUPER_ADMIN', 'BANNER_ADMIN', 'COMMENT_OPERATOR', 'NOTIFICATION_ADMIN', 'VIEWER', 'MEMBER', 'WEB_SERVICE_ADMIN', 'RULES_ENGINE_ADMIN', 'BRANCH_ADMIN', 'BRANCH_EMPLOYEE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminUserInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminUserInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "username": obj.get("username"),
            "password": obj.get("password"),
            "confirmPassword": obj.get("confirmPassword"),
            "name": obj.get("name"),
            "lastName": obj.get("lastName"),
            "isEnabled": obj.get("isEnabled"),
            "roles": obj.get("roles")
        })
        return _obj


