# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BannerOutput(BaseModel):
    """
    BannerOutput
    """ # noqa: E501
    id: Optional[StrictInt] = None
    image_id: Optional[StrictInt] = Field(default=None, alias="imageId")
    title: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    uri: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "imageId", "title", "message", "uri", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['HOME', 'SPEND_SCORE', 'ONLINE_CENTER', 'LOTTERY', 'IRAN_CARD', 'CHAMPIONS_LEAGUE_HOME', 'CHAMPIONS_LEAGUE_HOME_LOTTERY', 'CHAMPIONS_LEAGUE_LOTTERY', 'LUCKY_WHEEL', 'ONLINE_SHOPPING_MAIN', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_HEADER', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_HEADER_2', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_MAIN', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_BUTTON']):
            raise ValueError("must be one of enum values ('HOME', 'SPEND_SCORE', 'ONLINE_CENTER', 'LOTTERY', 'IRAN_CARD', 'CHAMPIONS_LEAGUE_HOME', 'CHAMPIONS_LEAGUE_HOME_LOTTERY', 'CHAMPIONS_LEAGUE_LOTTERY', 'LUCKY_WHEEL', 'ONLINE_SHOPPING_MAIN', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_HEADER', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_HEADER_2', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_MAIN', 'CHAMPIONS_LEAGUE_LOTTERY_PANEL_BUTTON')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BannerOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BannerOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "imageId": obj.get("imageId"),
            "title": obj.get("title"),
            "message": obj.get("message"),
            "uri": obj.get("uri"),
            "type": obj.get("type")
        })
        return _obj


