# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ChampionsLeagueLuckyWheelItemInput(BaseModel):
    """
    ChampionsLeagueLuckyWheelItemInput
    """ # noqa: E501
    prize_title: StrictStr = Field(alias="prizeTitle")
    display_percent: StrictInt = Field(alias="displayPercent")
    real_percent: StrictInt = Field(alias="realPercent")
    value: Optional[StrictInt] = None
    prize_type: StrictStr = Field(alias="prizeType")
    __properties: ClassVar[List[str]] = ["prizeTitle", "displayPercent", "realPercent", "value", "prizeType"]

    @field_validator('prize_type')
    def prize_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SCORE', 'GEM', 'OTHER']):
            raise ValueError("must be one of enum values ('SCORE', 'GEM', 'OTHER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChampionsLeagueLuckyWheelItemInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChampionsLeagueLuckyWheelItemInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prizeTitle": obj.get("prizeTitle"),
            "displayPercent": obj.get("displayPercent"),
            "realPercent": obj.get("realPercent"),
            "value": obj.get("value"),
            "prizeType": obj.get("prizeType")
        })
        return _obj


