# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CommentOutput(BaseModel):
    """
    CommentOutput
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    customer_number: Optional[StrictStr] = Field(default=None, alias="customerNumber")
    mobile_numbers: Optional[StrictStr] = Field(default=None, alias="mobileNumbers")
    profile_picture_id: Optional[StrictInt] = Field(default=None, alias="profilePictureId")
    user_level_type: Optional[StrictStr] = Field(default=None, alias="userLevelType")
    rate: Optional[StrictInt] = None
    message: Optional[StrictStr] = None
    shop_title: Optional[StrictStr] = Field(default=None, alias="shopTitle")
    logo_id: Optional[StrictInt] = Field(default=None, alias="logoId")
    create_date: Optional[datetime] = Field(default=None, alias="createDate")
    comment_condition: Optional[StrictStr] = Field(default=None, alias="commentCondition")
    __properties: ClassVar[List[str]] = ["id", "name", "customerNumber", "mobileNumbers", "profilePictureId", "userLevelType", "rate", "message", "shopTitle", "logoId", "createDate", "commentCondition"]

    @field_validator('comment_condition')
    def comment_condition_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACCEPT', 'PENDING', 'REJECT']):
            raise ValueError("must be one of enum values ('ACCEPT', 'PENDING', 'REJECT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommentOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommentOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "customerNumber": obj.get("customerNumber"),
            "mobileNumbers": obj.get("mobileNumbers"),
            "profilePictureId": obj.get("profilePictureId"),
            "userLevelType": obj.get("userLevelType"),
            "rate": obj.get("rate"),
            "message": obj.get("message"),
            "shopTitle": obj.get("shopTitle"),
            "logoId": obj.get("logoId"),
            "createDate": obj.get("createDate"),
            "commentCondition": obj.get("commentCondition")
        })
        return _obj


