# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.banner_output import BannerOutput
from openapi_client.models.online_center_category_output import OnlineCenterCategoryOutput
from typing import Optional, Set
from typing_extensions import Self

class OnlineCenterCategoryHomeOutput(BaseModel):
    """
    OnlineCenterCategoryHomeOutput
    """ # noqa: E501
    lottery_banners: Optional[List[BannerOutput]] = Field(default=None, alias="lotteryBanners")
    online_center_categories: Optional[List[OnlineCenterCategoryOutput]] = Field(default=None, alias="onlineCenterCategories")
    __properties: ClassVar[List[str]] = ["lotteryBanners", "onlineCenterCategories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OnlineCenterCategoryHomeOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lottery_banners (list)
        _items = []
        if self.lottery_banners:
            for _item_lottery_banners in self.lottery_banners:
                if _item_lottery_banners:
                    _items.append(_item_lottery_banners.to_dict())
            _dict['lotteryBanners'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in online_center_categories (list)
        _items = []
        if self.online_center_categories:
            for _item_online_center_categories in self.online_center_categories:
                if _item_online_center_categories:
                    _items.append(_item_online_center_categories.to_dict())
            _dict['onlineCenterCategories'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OnlineCenterCategoryHomeOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lotteryBanners": [BannerOutput.from_dict(_item) for _item in obj["lotteryBanners"]] if obj.get("lotteryBanners") is not None else None,
            "onlineCenterCategories": [OnlineCenterCategoryOutput.from_dict(_item) for _item in obj["onlineCenterCategories"]] if obj.get("onlineCenterCategories") is not None else None
        })
        return _obj


