# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PayBillVoucherOutput(BaseModel):
    """
    PayBillVoucherOutput
    """ # noqa: E501
    user_level: Optional[StrictStr] = Field(default=None, alias="userLevel")
    bill_id: Optional[StrictStr] = Field(default=None, alias="billId")
    reference_id: Optional[StrictStr] = Field(default=None, alias="referenceId")
    cost: Optional[StrictInt] = None
    score_count: Optional[StrictInt] = Field(default=None, alias="scoreCount")
    bill_type: Optional[StrictStr] = Field(default=None, alias="billType")
    date_time: Optional[datetime] = Field(default=None, alias="dateTime")
    purchase_type: Optional[StrictStr] = Field(default=None, alias="purchaseType")
    __properties: ClassVar[List[str]] = ["userLevel", "billId", "referenceId", "cost", "scoreCount", "billType", "dateTime", "purchaseType"]

    @field_validator('bill_type')
    def bill_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['WATER', 'POWER', 'GAS', 'TELEPHONE', 'MOBILE', 'MUNICIPALITY']):
            raise ValueError("must be one of enum values ('WATER', 'POWER', 'GAS', 'TELEPHONE', 'MOBILE', 'MUNICIPALITY')")
        return value

    @field_validator('purchase_type')
    def purchase_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ONLINE_CENTER', 'LOTTERY', 'CHARITY', 'GIFT', 'INSURANCE', 'BILL', 'EXCHANGE', 'IRAN_MALL_CINEMA']):
            raise ValueError("must be one of enum values ('ONLINE_CENTER', 'LOTTERY', 'CHARITY', 'GIFT', 'INSURANCE', 'BILL', 'EXCHANGE', 'IRAN_MALL_CINEMA')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayBillVoucherOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayBillVoucherOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userLevel": obj.get("userLevel"),
            "billId": obj.get("billId"),
            "referenceId": obj.get("referenceId"),
            "cost": obj.get("cost"),
            "scoreCount": obj.get("scoreCount"),
            "billType": obj.get("billType"),
            "dateTime": obj.get("dateTime"),
            "purchaseType": obj.get("purchaseType")
        })
        return _obj


