# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legal_person import LegalPerson
from openapi_client.models.natural_person import NaturalPerson
from typing import Optional, Set
from typing_extensions import Self

class Person(BaseModel):
    """
    Person
    """ # noqa: E501
    id: Optional[StrictInt] = None
    type: Optional[StrictStr] = None
    natural_person: Optional[NaturalPerson] = Field(default=None, alias="naturalPerson")
    legal_person: Optional[LegalPerson] = Field(default=None, alias="legalPerson")
    full_name: Optional[StrictStr] = Field(default=None, alias="fullName")
    uniq_string: Optional[StrictStr] = Field(default=None, alias="uniqString")
    email: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "type", "naturalPerson", "legalPerson", "fullName", "uniqString", "email", "phone"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NATURAL', 'LEGAL']):
            raise ValueError("must be one of enum values ('NATURAL', 'LEGAL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Person from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of natural_person
        if self.natural_person:
            _dict['naturalPerson'] = self.natural_person.to_dict()
        # override the default output from pydantic by calling `to_dict()` of legal_person
        if self.legal_person:
            _dict['legalPerson'] = self.legal_person.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Person from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "naturalPerson": NaturalPerson.from_dict(obj["naturalPerson"]) if obj.get("naturalPerson") is not None else None,
            "legalPerson": LegalPerson.from_dict(obj["legalPerson"]) if obj.get("legalPerson") is not None else None,
            "fullName": obj.get("fullName"),
            "uniqString": obj.get("uniqString"),
            "email": obj.get("email"),
            "phone": obj.get("phone")
        })
        return _obj


