# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ReportUserBadgeOutput(BaseModel):
    """
    ReportUserBadgeOutput
    """ # noqa: E501
    id: Optional[StrictInt] = None
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    user_level_type: Optional[StrictStr] = Field(default=None, alias="userLevelType")
    dast_be_code: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dastBeCode")
    hatam_tayi: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="hatamTayi")
    nokte_sanj: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="nokteSanj")
    electro_baz: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="electroBaz")
    meh_tar: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="mehTar")
    khosh_shans: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="khoshShans")
    hamrah: Optional[Union[StrictFloat, StrictInt]] = None
    saheb_nazar: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="sahebNazar")
    majarajoo: Optional[Union[StrictFloat, StrictInt]] = None
    peygir: Optional[Union[StrictFloat, StrictInt]] = None
    accelerator5: Optional[Union[StrictFloat, StrictInt]] = None
    accelerator8: Optional[Union[StrictFloat, StrictInt]] = None
    customer_number: Optional[StrictInt] = Field(default=None, alias="customerNumber")
    mobile_number: Optional[StrictStr] = Field(default=None, alias="mobileNumber")
    __properties: ClassVar[List[str]] = ["id", "firstName", "lastName", "userLevelType", "dastBeCode", "hatamTayi", "nokteSanj", "electroBaz", "mehTar", "khoshShans", "hamrah", "sahebNazar", "majarajoo", "peygir", "accelerator5", "accelerator8", "customerNumber", "mobileNumber"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportUserBadgeOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportUserBadgeOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "userLevelType": obj.get("userLevelType"),
            "dastBeCode": obj.get("dastBeCode"),
            "hatamTayi": obj.get("hatamTayi"),
            "nokteSanj": obj.get("nokteSanj"),
            "electroBaz": obj.get("electroBaz"),
            "mehTar": obj.get("mehTar"),
            "khoshShans": obj.get("khoshShans"),
            "hamrah": obj.get("hamrah"),
            "sahebNazar": obj.get("sahebNazar"),
            "majarajoo": obj.get("majarajoo"),
            "peygir": obj.get("peygir"),
            "accelerator5": obj.get("accelerator5"),
            "accelerator8": obj.get("accelerator8"),
            "customerNumber": obj.get("customerNumber"),
            "mobileNumber": obj.get("mobileNumber")
        })
        return _obj


