# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RuleConfigRequestUpdateInput(BaseModel):
    """
    RuleConfigRequestUpdateInput
    """ # noqa: E501
    score_type_id: Optional[StrictInt] = Field(default=None, alias="scoreTypeId")
    period_day: Optional[StrictInt] = Field(default=None, alias="periodDay")
    period_max_day: Optional[StrictInt] = Field(default=None, alias="periodMaxDay")
    min_unit: Optional[StrictStr] = Field(default=None, alias="minUnit")
    min_unit_value: Optional[StrictInt] = Field(default=None, alias="minUnitValue")
    max_unit_value: Optional[StrictInt] = Field(default=None, alias="maxUnitValue")
    score: Optional[StrictInt] = None
    max_score_period_day: Optional[StrictInt] = Field(default=None, alias="maxScorePeriodDay")
    max_score_max_period_day: Optional[StrictInt] = Field(default=None, alias="maxScoreMaxPeriodDay")
    customer_level_id: Optional[StrictInt] = Field(default=None, alias="customerLevelId")
    group_id: Optional[StrictInt] = Field(default=None, alias="groupId")
    check_validator: Optional[StrictBool] = Field(default=None, alias="checkValidator")
    min_checksum_value: Optional[StrictInt] = Field(default=None, alias="minChecksumValue")
    min_check_count_value: Optional[StrictInt] = Field(default=None, alias="minCheckCountValue")
    unit_measure: Optional[StrictStr] = Field(default=None, alias="unitMeasure")
    max_checksum_value: Optional[StrictInt] = Field(default=None, alias="maxChecksumValue")
    max_check_count_value: Optional[StrictInt] = Field(default=None, alias="maxCheckCountValue")
    description: Optional[StrictStr] = None
    effective_date: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="effectiveDate")
    disable_date: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="disableDate")
    __properties: ClassVar[List[str]] = ["scoreTypeId", "periodDay", "periodMaxDay", "minUnit", "minUnitValue", "maxUnitValue", "score", "maxScorePeriodDay", "maxScoreMaxPeriodDay", "customerLevelId", "groupId", "checkValidator", "minChecksumValue", "minCheckCountValue", "unitMeasure", "maxChecksumValue", "maxCheckCountValue", "description", "effectiveDate", "disableDate"]

    @field_validator('effective_date')
    def effective_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d{4}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/")
        return value

    @field_validator('disable_date')
    def disable_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d{4}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleConfigRequestUpdateInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleConfigRequestUpdateInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scoreTypeId": obj.get("scoreTypeId"),
            "periodDay": obj.get("periodDay"),
            "periodMaxDay": obj.get("periodMaxDay"),
            "minUnit": obj.get("minUnit"),
            "minUnitValue": obj.get("minUnitValue"),
            "maxUnitValue": obj.get("maxUnitValue"),
            "score": obj.get("score"),
            "maxScorePeriodDay": obj.get("maxScorePeriodDay"),
            "maxScoreMaxPeriodDay": obj.get("maxScoreMaxPeriodDay"),
            "customerLevelId": obj.get("customerLevelId"),
            "groupId": obj.get("groupId"),
            "checkValidator": obj.get("checkValidator"),
            "minChecksumValue": obj.get("minChecksumValue"),
            "minCheckCountValue": obj.get("minCheckCountValue"),
            "unitMeasure": obj.get("unitMeasure"),
            "maxChecksumValue": obj.get("maxChecksumValue"),
            "maxCheckCountValue": obj.get("maxCheckCountValue"),
            "description": obj.get("description"),
            "effectiveDate": obj.get("effectiveDate"),
            "disableDate": obj.get("disableDate")
        })
        return _obj


