# coding: utf-8

"""
    Club Customer

    Farazpardazan Company

    The version of the OpenAPI document: v1
    Contact: HamedHaeri.dev@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserProfileDetailsInput(BaseModel):
    """
    UserProfileDetailsInput
    """ # noqa: E501
    id: Optional[StrictInt] = None
    profile_picture_id: Optional[StrictInt] = Field(default=None, alias="profilePictureId")
    customer_number: Optional[StrictInt] = Field(default=None, alias="customerNumber")
    user_level_type: Optional[StrictStr] = Field(default=None, alias="userLevelType")
    is_show_name: StrictBool = Field(alias="isShowName")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    national_id: Optional[StrictStr] = Field(default=None, alias="nationalId")
    mobile_number: Optional[StrictStr] = Field(default=None, alias="mobileNumber")
    birthday: Optional[datetime] = None
    father_name: Optional[StrictStr] = Field(default=None, alias="fatherName")
    job: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    address: Optional[StrictStr] = None
    education: Optional[StrictStr] = None
    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    telephone: Optional[StrictStr] = None
    marital_status: Optional[StrictStr] = Field(default=None, alias="maritalStatus")
    married_time: Optional[datetime] = Field(default=None, alias="marriedTime")
    children_count: Optional[StrictInt] = Field(default=None, alias="childrenCount")
    children_birthday_time: Optional[List[datetime]] = Field(default=None, alias="childrenBirthdayTime")
    complete: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "profilePictureId", "customerNumber", "userLevelType", "isShowName", "firstName", "lastName", "nationalId", "mobileNumber", "birthday", "fatherName", "job", "email", "address", "education", "postalCode", "telephone", "maritalStatus", "marriedTime", "childrenCount", "childrenBirthdayTime", "complete"]

    @field_validator('marital_status')
    def marital_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SINGLE', 'MARRIED']):
            raise ValueError("must be one of enum values ('SINGLE', 'MARRIED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserProfileDetailsInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserProfileDetailsInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "profilePictureId": obj.get("profilePictureId"),
            "customerNumber": obj.get("customerNumber"),
            "userLevelType": obj.get("userLevelType"),
            "isShowName": obj.get("isShowName"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "nationalId": obj.get("nationalId"),
            "mobileNumber": obj.get("mobileNumber"),
            "birthday": obj.get("birthday"),
            "fatherName": obj.get("fatherName"),
            "job": obj.get("job"),
            "email": obj.get("email"),
            "address": obj.get("address"),
            "education": obj.get("education"),
            "postalCode": obj.get("postalCode"),
            "telephone": obj.get("telephone"),
            "maritalStatus": obj.get("maritalStatus"),
            "marriedTime": obj.get("marriedTime"),
            "childrenCount": obj.get("childrenCount"),
            "childrenBirthdayTime": obj.get("childrenBirthdayTime"),
            "complete": obj.get("complete")
        })
        return _obj


